/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"fmt"
	"strings"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	networkingv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	gatewayv1 "sigs.k8s.io/gateway-api/apis/v1"
)

var _ = Describe("Ingress Controller", func() {
	Context("When reconciling a resource", func() {
		const (
			IngressName      = "test-ingress"
			IngressNamespace = "default"
		)

		ctx := context.Background()

		namespacedName := types.NamespacedName{
			Name:      IngressName,
			Namespace: IngressNamespace,
		}

		BeforeEach(func() {
			By("cleaning up resources")
			// No-op for now as we use fresh names if needed, but good practice
		})

		It("should successfully reconcile with a default parent Gateway", func() {
			By("creating the Ingress reconciler with a default parent Gateway")
			reconciler := &IngressReconciler{
				Client:               k8sClient,
				Scheme:               k8sClient.Scheme(),
				DefaultParentGateway: "default-gw",
			}

			By("creating an Ingress resource")
			ingress := &networkingv1.Ingress{
				ObjectMeta: metav1.ObjectMeta{
					Name:      IngressName,
					Namespace: IngressNamespace,
				},
				Spec: networkingv1.IngressSpec{
					Rules: []networkingv1.IngressRule{
						{
							Host: "example.com",
							IngressRuleValue: networkingv1.IngressRuleValue{
								HTTP: &networkingv1.HTTPIngressRuleValue{
									Paths: []networkingv1.HTTPIngressPath{
										{
											Path:     "/",
											PathType: func() *networkingv1.PathType { pt := networkingv1.PathTypePrefix; return &pt }(),
											Backend: networkingv1.IngressBackend{
												Service: &networkingv1.IngressServiceBackend{
													Name: "test-service",
													Port: networkingv1.ServiceBackendPort{
														Number: 80,
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			}
			Expect(k8sClient.Create(ctx, ingress)).Should(Succeed())

			By("reconciling the Ingress")
			_, err := reconciler.Reconcile(ctx, ctrl.Request{NamespacedName: namespacedName})
			Expect(err).NotTo(HaveOccurred())

			By("verifying the HTTPRoute has the default parent Gateway")
			// HTTPRoute name is usually generated by i2gw. For one rule it's often the ingress name or host.
			// Let's list HTTPRoutes in the namespace.
			routes := &gatewayv1.HTTPRouteList{}
			Eventually(func() bool {
				err := k8sClient.List(ctx, routes, client.InNamespace(IngressNamespace))
				return err == nil && len(routes.Items) > 0
			}, "10s", "1s").Should(BeTrue())

			found := false
			for _, route := range routes.Items {
				if len(route.Spec.ParentRefs) > 0 {
					if route.Spec.ParentRefs[0].Name == "default-gw" {
						found = true
						break
					}
				}
			}
			Expect(found).To(BeTrue(), "HTTPRoute should have default-gw as parent ref")
		})

		It("should override the default parent Gateway with an annotation", func() {
			By("creating the Ingress reconciler with a default parent Gateway")
			reconciler := &IngressReconciler{
				Client:               k8sClient,
				Scheme:               k8sClient.Scheme(),
				DefaultParentGateway: "default-gw",
			}

			By("creating an Ingress resource with override annotation")
			ingressName := "override-ingress"
			ingress := &networkingv1.Ingress{
				ObjectMeta: metav1.ObjectMeta{
					Name:      ingressName,
					Namespace: IngressNamespace,
					Annotations: map[string]string{
						"ingress2gateway.viu.ca/parent-gateway": "annotated-gw",
					},
				},
				Spec: networkingv1.IngressSpec{
					Rules: []networkingv1.IngressRule{
						{
							Host: "override.example.com",
							IngressRuleValue: networkingv1.IngressRuleValue{
								HTTP: &networkingv1.HTTPIngressRuleValue{
									Paths: []networkingv1.HTTPIngressPath{
										{
											Path:     "/",
											PathType: func() *networkingv1.PathType { pt := networkingv1.PathTypePrefix; return &pt }(),
											Backend: networkingv1.IngressBackend{
												Service: &networkingv1.IngressServiceBackend{
													Name: "test-service",
													Port: networkingv1.ServiceBackendPort{
														Number: 80,
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			}
			Expect(k8sClient.Create(ctx, ingress)).Should(Succeed())

			By("reconciling the Ingress")
			_, err := reconciler.Reconcile(ctx, ctrl.Request{NamespacedName: types.NamespacedName{Name: ingressName, Namespace: IngressNamespace}})
			Expect(err).NotTo(HaveOccurred())

			By("verifying the HTTPRoute has the annotated parent Gateway")
			routes := &gatewayv1.HTTPRouteList{}
			Eventually(func() bool {
				err := k8sClient.List(ctx, routes, client.InNamespace(IngressNamespace))
				if err != nil || len(routes.Items) == 0 {
					return false
				}
				for _, route := range routes.Items {
					// Check for host to identify the right route
					if len(route.Spec.Hostnames) > 0 && route.Spec.Hostnames[0] == "override.example.com" {
						if len(route.Spec.ParentRefs) > 0 && route.Spec.ParentRefs[0].Name == "annotated-gw" {
							return true
						}
					}
				}
				return false
			}, "10s", "1s").Should(BeTrue())
		})

		It("should handle namespaced parent Gateway references in annotations", func() {
			By("creating the Ingress reconciler")
			reconciler := &IngressReconciler{
				Client: k8sClient,
				Scheme: k8sClient.Scheme(),
			}

			By("creating an Ingress resource with namespaced override annotation")
			ingressName := "namespaced-ingress"
			ingress := &networkingv1.Ingress{
				ObjectMeta: metav1.ObjectMeta{
					Name:      ingressName,
					Namespace: IngressNamespace,
					Annotations: map[string]string{
						"ingress2gateway.viu.ca/parent-gateway": "other-ns/namespaced-gw",
					},
				},
				Spec: networkingv1.IngressSpec{
					Rules: []networkingv1.IngressRule{
						{
							Host: "namespaced.example.com",
							IngressRuleValue: networkingv1.IngressRuleValue{
								HTTP: &networkingv1.HTTPIngressRuleValue{
									Paths: []networkingv1.HTTPIngressPath{
										{
											Path:     "/",
											PathType: func() *networkingv1.PathType { pt := networkingv1.PathTypePrefix; return &pt }(),
											Backend: networkingv1.IngressBackend{
												Service: &networkingv1.IngressServiceBackend{
													Name: "test-service",
													Port: networkingv1.ServiceBackendPort{
														Number: 80,
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			}
			Expect(k8sClient.Create(ctx, ingress)).Should(Succeed())

			By("reconciling the Ingress")
			_, err := reconciler.Reconcile(ctx, ctrl.Request{NamespacedName: types.NamespacedName{Name: ingressName, Namespace: IngressNamespace}})
			Expect(err).NotTo(HaveOccurred())

			By("verifying the HTTPRoute has the namespaced parent Gateway")
			routes := &gatewayv1.HTTPRouteList{}
			Eventually(func() bool {
				err := k8sClient.List(ctx, routes, client.InNamespace(IngressNamespace))
				if err != nil {
					return false
				}
				for _, route := range routes.Items {
					if len(route.Spec.Hostnames) > 0 && route.Spec.Hostnames[0] == "namespaced.example.com" {
						if len(route.Spec.ParentRefs) > 0 {
							ref := route.Spec.ParentRefs[0]
							return ref.Name == "namespaced-gw" && ref.Namespace != nil && string(*ref.Namespace) == "other-ns"
						}
					}
				}
				return false
			}, "10s", "1s").Should(BeTrue())
		})

		DescribeTable("Ingress Class Filtering",
			func(configuredClass string, ingressClass *string, annotationClass string, expectedProcessed bool) {
				By("creating the Ingress reconciler with configured class")
				reconciler := &IngressReconciler{
					Client:           k8sClient,
					Scheme:           k8sClient.Scheme(),
					IngressClassName: configuredClass,
				}

				ingressName := "filter-test-" + strings.ToLower(fmt.Sprintf("%v-%v-%v", configuredClass, ingressClass, annotationClass))
				// Sanitize name for k8s and add timestamp for uniqueness
				ingressName = strings.ReplaceAll(ingressName, "<nil>", "none")
				ingressName = strings.ReplaceAll(ingressName, "*", "")
				ingressName = fmt.Sprintf("%s-%d", ingressName, time.Now().UnixNano()%1000000)
				if len(ingressName) > 63 {
					ingressName = ingressName[:63]
				}

				hostName := ingressName + ".example.com"

				By("creating an Ingress resource")
				annotations := make(map[string]string)
				if annotationClass != "" {
					annotations["kubernetes.io/ingress.class"] = annotationClass
				}

				ingress := &networkingv1.Ingress{
					ObjectMeta: metav1.ObjectMeta{
						Name:        ingressName,
						Namespace:   IngressNamespace,
						Annotations: annotations,
					},
					Spec: networkingv1.IngressSpec{
						IngressClassName: ingressClass,
						Rules: []networkingv1.IngressRule{
							{
								Host: hostName,
								IngressRuleValue: networkingv1.IngressRuleValue{
									HTTP: &networkingv1.HTTPIngressRuleValue{
										Paths: []networkingv1.HTTPIngressPath{
											{
												Path:     "/",
												PathType: func() *networkingv1.PathType { pt := networkingv1.PathTypePrefix; return &pt }(),
												Backend: networkingv1.IngressBackend{
													Service: &networkingv1.IngressServiceBackend{
														Name: "test-service",
														Port: networkingv1.ServiceBackendPort{
															Number: 80,
														},
													},
												},
											},
										},
									},
								},
							},
						},
					},
				}
				Expect(k8sClient.Create(ctx, ingress)).Should(Succeed())

				By("reconciling the Ingress")
				_, err := reconciler.Reconcile(ctx, ctrl.Request{NamespacedName: types.NamespacedName{Name: ingressName, Namespace: IngressNamespace}})
				Expect(err).NotTo(HaveOccurred())

				By("verifying reconciliation result")
				Eventually(func() bool {
					routes := &gatewayv1.HTTPRouteList{}
					err := k8sClient.List(ctx, routes, client.InNamespace(IngressNamespace))
					if err != nil {
						return false
					}
					found := false
					for _, route := range routes.Items {
						if len(route.Spec.Hostnames) > 0 && string(route.Spec.Hostnames[0]) == hostName {
							found = true
							break
						}
					}
					return found == expectedProcessed
				}, "10s", "100ms").Should(BeTrue())
			},
			Entry("Matches IngressClassName", "my-class", func() *string { s := "my-class"; return &s }(), "", true),
			Entry("Matches legacy annotation", "my-class", nil, "my-class", true),
			Entry("Mismatches IngressClassName", "my-class", func() *string { s := "other-class"; return &s }(), "", false),
			Entry("Mismatches legacy annotation", "my-class", nil, "other-class", false),
			Entry("Processes all when no class configured", "", func() *string { s := "any-class"; return &s }(), "", true),
			Entry("Ignores when class required but missing", "my-class", nil, "", false),
		)
	})
})
